In [1856]:
import pandas as pd
import datetime as dt
from bs4 import BeautifulSoup

In [1857]:
#logs
gamelogs = pd.read_csv('gamelogs_min_23.csv', index_col=0)
shooting_ps = pd.read_csv('shooting_formatted_2023.csv', index_col=0)
shooting_logs = pd.read_csv('player_logs_shooting_23.csv', index_col=0)
pass_drives = pd.read_csv('drives_pass_2023_reformat.csv', index_col=0)
rebs_gl = pd.read_csv('player_logs_rebs_23.csv', index_col=0)
ptypes = pd.read_csv('/Users/sethmiller/Documents/NBA/NBA 2022-23 Season/player_types_22.csv', index_col=0)

#def today
shooting_def_tm = pd.read_csv('shooting_def_tm_2023.csv', index_col=0)
shooting_def_pr = pd.read_csv('shooting_def_pr_NBA_2023.csv', index_col=0)
shooting_def_pr1 = pd.read_csv('shooting_def_pr_tm_2023.csv', index_col=0)
shooting_d = pd.read_csv('def_dif_pr_team_2023.csv')
shooting3p_def_tm = pd.read_csv('3p_shooting_def_q2023.csv', index_col=0)
shooting3p_def_pr1 = pd.read_csv('3p_shooting_def_pr2023.csv', index_col=0)
drives_player = pd.read_csv('drives_player_2023.csv', index_col=0)
drives_team_vs = pd.read_csv('drives_team_vs_2023.csv', index_col=0)
rebs_team1 = pd.read_csv('rebs_team_2023.csv', index_col=0)
rebs_players1 = pd.read_csv('rebs_players_2023.csv', index_col=0)
threes_plus2 =  pd.read_csv('threes_plus2_def_23.csv', index_col=0)
threes_plus =  pd.read_csv('threes_plus_def_23.csv', index_col=0)
mid_plus =  pd.read_csv('mid_plus_def_23.csv', index_col=0)
paint_plus =  pd.read_csv('paint_plus_def_23.csv', index_col=0)

dh_logs =  pd.read_csv('dh_logs.csv', index_col=0)
pnr_logs =  pd.read_csv('pnr_logs.csv', index_col=0)
pnp_logs =  pd.read_csv('pnp_logs.csv', index_col=0)
threes_logs =  pd.read_csv('threes_logs.csv', index_col=0)
creator_logs =  pd.read_csv('creator_logs.csv', index_col=0)
secondary_logs =  pd.read_csv('secondary_logs.csv', index_col=0)
sc_logs =  pd.read_csv('sc_logs.csv', index_col=0)

pnp_3logs =  pd.read_csv('pnp_3logs.csv', index_col=0)
threes_3logs =  pd.read_csv('threes_3logs.csv', index_col=0)
creator_3logs =  pd.read_csv('creator_3logs.csv', index_col=0)
secondary_3logs =  pd.read_csv('secondary_3logs.csv', index_col=0)

dh = pd.read_csv('dh_def23.csv', index_col=0)
pnr = pd.read_csv('pnr_def23.csv', index_col=0)
pnp= pd.read_csv('pnp_def23.csv', index_col=0)
threes_d = pd.read_csv('threes_def23.csv', index_col=0)
creator_d = pd.read_csv('creator_def23.csv', index_col=0)
secondary_d = pd.read_csv('secondary_def23.csv', index_col=0)
sc_d = pd.read_csv('sc_def23.csv', index_col=0)

BigMen_d = pd.read_csv('BigMen_def23.csv', index_col=0)
BHReb_d = pd.read_csv('BHReb_def23.csv', index_col=0)
WingReb_d = pd.read_csv('WingReb_def23.csv', index_col=0)

bigmen_logs = pd.read_csv('bigmen_rebs.csv', index_col=0)
wing_logs = pd.read_csv('wings_rebs.csv', index_col=0)
BH_logs = pd.read_csv('BH_rebs.csv',index_col=0)

In [1858]:
downhill23 = pd.read_csv('downhill23.csv', index_col = 0)
picknroll23 = pd.read_csv('picknroll23.csv', index_col = 0)
picknpop23 = pd.read_csv('picknpop23.csv', index_col = 0)
threes23 = pd.read_csv('3pt23.csv', index_col = 0)
creator23 = pd.read_csv('ShotCreator23.csv', index_col = 0)
secondary23 = pd.read_csv('SecondaryShooters23.csv', index_col = 0)
sc23 = pd.read_csv('SecondaryCreators23.csv', index_col = 0)

downhill22 = pd.read_csv('/Users/sethmiller/Documents/NBA/NBA 2022-23 Season/downhill22.csv', index_col = 0)
picknroll22 = pd.read_csv('/Users/sethmiller/Documents/NBA/NBA 2022-23 Season/picknroll22.csv', index_col = 0)
picknpop22 = pd.read_csv('/Users/sethmiller/Documents/NBA/NBA 2022-23 Season/picknpop22.csv', index_col = 0)
threes22 = pd.read_csv('/Users/sethmiller/Documents/NBA/NBA 2022-23 Season/3pt22.csv', index_col = 0)
creator22 = pd.read_csv('/Users/sethmiller/Documents/NBA/NBA 2022-23 Season/ShotCreator22.csv', index_col = 0)
secondary22 = pd.read_csv('/Users/sethmiller/Documents/NBA/NBA 2022-23 Season/SecondaryShooters22.csv', index_col = 0)


#downhill = pd.concat([downhill22[['PLAYER','Downhill']],downhill23[['PLAYER','Downhill']]]).drop_duplicates()
#picknroll = pd.concat([picknroll22[['PLAYER','PickNRoll']],picknroll23[['PLAYER','PickNRoll']]]).drop_duplicates()
#picknpop = pd.concat([picknpop22[['PLAYER','PickNPop']],picknpop23[['PLAYER','PickNPop']]]).drop_duplicates()
#threes = pd.concat([threes22[['PLAYER','3pt']],threes23[['PLAYER','3pt']]]).drop_duplicates()
#creator = pd.concat([creator22[['PLAYER','Shot Creator']],creator23[['PLAYER','Shot Creator']]]).drop_duplicates()
#secondary = pd.concat([secondary22[['PLAYER','Secondary Shooters']],secondary23[['PLAYER','Secondary Shooters']]]).drop_duplicates()


BigMen23 = pd.read_csv('BigMenReb23.csv', index_col = 0)
BHReb23 = pd.read_csv('BHReb23.csv', index_col = 0)
WingReb23 = pd.read_csv('WingReb23.csv', index_col = 0)

In [1859]:
#gamelogs[gamelogs['PLAYER']=='Mikal Bridges']

In [1860]:
from selenium import webdriver
#from webdriver_manager.safari import SafariDriverManager

#safaridriver = "/usr/local/bin/chrome"
#os.environ['webdriver.safari.driver'] = safaridriver
#web_driver = webdriver.Safari(executable_path='/usr/bin/safaridriver')
web_driver = webdriver.Safari()
#driver = webdriver.Chrome('/usr/local/bin/chromedriver')

# selenium 4
#from selenium import webdriver
#from selenium.webdriver.chrome.service import Service as ChromeService
#from webdriver_manager.chrome import ChromeDriverManager

#driver = webdriver.Chrome(ChromeDriverManager().install())

In [1861]:
td = dt.datetime.today().strftime("%Y-%m-%d")
bet_search =  'https://www.rotowire.com/basketball/nba-lineups.php'

web_driver.get(bet_search)
soup = BeautifulSoup(web_driver.page_source, 'html.parser')

In [1862]:
td

'2024-03-29'

In [1863]:
name = [x.get_text() for x in soup.find_all('div', class_='lineup__abbr')]
#names = [s.strip() for s in name]
away = [x.get_text() for x in soup.find_all('a', class_='lineup__team is-visit')]
aways = [s.strip() for s in away]
home = [x.get_text() for x in soup.find_all('a', class_='lineup__team is-home')]
homes = [s.strip() for s in home]

stats = [ homes, aways, ]
key = ['Home','Away']
intial = dict(zip(key, stats))
matchups = pd.DataFrame.from_dict(intial)
todays_tms = pd.DataFrame(name, columns=['TEAM_ABBR'])

sort1 =pd.merge(todays_tms, matchups, how='left', left_on='TEAM_ABBR',right_on='Home')

sort2 =pd.merge(todays_tms, matchups, how='left', left_on='TEAM_ABBR',right_on='Away')

sort1.dropna(inplace=True)
sort2.dropna(inplace=True)

matchups=[sort1,sort2]

team_td = pd.concat(matchups)
team_td.loc[team_td['TEAM_ABBR']!=team_td['Home'], 'OPPONENT']= team_td['Home']
team_td.loc[team_td['TEAM_ABBR']!=team_td['Away'], 'OPPONENT']= team_td['Away']
team_ = team_td[['TEAM_ABBR','OPPONENT']]

In [1864]:
from nba_api.stats.endpoints import commonallplayers
from nba_api.stats.library.parameters import Season
from nba_api.stats.library.parameters import SeasonType


s = commonallplayers.CommonAllPlayers(season='2023-24').get_normalized_dict()

games = s['CommonAllPlayers']
gl_add_23 = pd.DataFrame.from_dict(games)

In [1865]:
gl_add_24 = gl_add_23[gl_add_23['ROSTERSTATUS']==1]

In [1921]:
gl_add_23

,PERSON_ID,DISPLAY_LAST_COMMA_FIRST,DISPLAY_FIRST_LAST,ROSTERSTATUS,FROM_YEAR,TO_YEAR,PLAYERCODE,PLAYER_SLUG,TEAM_ID,TEAM_CITY,TEAM_NAME,TEAM_ABBREVIATION,TEAM_CODE,TEAM_SLUG,GAMES_PLAYED_FLAG,OTHERLEAGUE_EXPERIENCE_CH
0,76001,"Abdelnaby, Alaa",Alaa Abdelnaby,0,1990,1994,HISTADD_alaa_abdelnaby,alaa_abdelnaby,0,,,,,None,Y,00
1,76002,"Abdul-Aziz, Zaid",Zaid Abdul-Aziz,0,1968,1977,HISTADD_zaid_abdul-aziz,zaid_abdul-aziz,0,,,,,None,Y,00
2,76003,"Abdul-Jabbar, Kareem",Kareem Abdul-Jabbar,0,1969,1988,HISTADD_kareem_abdul-jabbar,kareem_abdul-jabbar,0,,,,,None,Y,00
3,51,"Abdul-Rauf, Mahmoud",Mahmoud Abdul-Rauf,0,1990,2000,mahmoud_abdul-rauf,mahmoud_abdul-rauf,0,,,,,None,Y,00
4,1505,"Abdul-Wahad, Tariq",Tariq Abdul-Wahad,0,1997,2003,tariq_abdul-wahad,tariq_abdul-wahad,0,,,,,None,Y,00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4913,1627790,"Zizic, Ante",Ante Zizic,0,2017,2019,ante_zizic,ante_zizic,0,,,,,None,Y,01
4914,78647,"Zoet, Jim",Jim Zoet,0,1982,1982,HISTADD_jim_zoet,jim_zoet,0,,,,,None,Y,00
4915,78648,"Zopf, Bill",Bill Zopf,0,1970,1970,HISTADD_zip_zopf,bill_zopf,0,,,,,None,Y,00
4916,1627826,"Zubac, Ivica",Ivica Zubac,1,2016,2023,ivica_zubac,ivica_zubac,1610612746,LA,Clippers,LAC,clippers,clippers,Y,01
4917,78650,"Zunic, Matt",Matt Zunic,0,1948,1948,HISTADD_matt_zunic,matt_zunic,0,,,,,None,Y,00

In [1866]:
players = gl_add_24.loc[gl_add_24['TEAM_ABBREVIATION']!='']
players_ = players[['DISPLAY_FIRST_LAST','TEAM_ABBREVIATION']]
players_.rename(columns={'DISPLAY_FIRST_LAST':'PLAYER','TEAM_ABBREVIATION':'TEAM_ABBR'}, inplace=True)
playing_td = team_.merge(players_).rename(columns={'TEAM_ABBR':'TEAM'})

/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/1923986078.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  players_.rename(columns={'DISPLAY_FIRST_LAST':'PLAYER','TEAM_ABBREVIATION':'TEAM_ABBR'}, inplace=True)

In [1867]:
gamelogs.rename(columns={'PLAYER_NAME':'PLAYER'},inplace=True)

In [1868]:
gamelogs.drop_duplicates(inplace=True)

In [1869]:
gamelogs['OPPONENT'] = gamelogs['MATCHUP'].str.strip().str[-3:]

In [1870]:
players = gamelogs.groupby('PLAYER').agg({'MIN': 'mean','PTS': 'mean','REB': 'mean','AST': 'mean','FG3M': 'mean', 'GAME_DATE': 'count'}).round(2).reset_index()

In [1871]:
players_gen = players.merge(ptypes[['PLAYER','player_roles']], how='left')

In [1872]:
shooting_logs.loc[shooting_logs['player_roles'].isna(), 'player_roles']='None'
players_gen.loc[players_gen['player_roles'].isna(), 'player_roles']='None'

In [1873]:
def get_shooting_prob(df_slice):
    x={}
    
    x['WO_paint_(%)'] = df_slice['2FGM_WO_paint'].sum()/df_slice['2FGA_WO_paint'].sum()
    x['WO_paint_rate'] = (df_slice['2FGA_WO_paint'].sum()/df_slice['MIN'].sum())*36
    x['O_paint_(%)'] = df_slice['2FGM_O_paint'].sum()/df_slice['2FGA_O_paint'].sum()
    x['O_paint_rate'] = (df_slice['2FGA_O_paint'].sum()/df_slice['MIN'].sum())*36
    x['T_paint_(%)'] = df_slice['2FGM_T_paint'].sum()/df_slice['2FGA_T_paint'].sum()
    x['T_paint_rate'] = (df_slice['2FGA_T_paint'].sum()/df_slice['MIN'].sum())*36
    x['VT_paint_(%)'] = df_slice['2FGM_VT_paint'].sum()/df_slice['2FGA_VT_paint'].sum()
    x['VT_paint_rate'] = (df_slice['2FGA_VT_paint'].sum()/df_slice['MIN'].sum())*36
    x['Tot_paint_(%)'] = df_slice['2FGM_paint'].sum()/df_slice['2FGA_paint'].sum()
    x['Tot_paint_rate'] = (df_slice['2FGA_paint'].sum()/df_slice['MIN'].sum())*36
    
    x['WO_mid_(%)'] = df_slice['2FGM_WO_10'].sum()/df_slice['2FGA_WO_10'].sum()
    x['WO_mid_rate'] = (df_slice['2FGA_WO_10'].sum()/df_slice['MIN'].sum())*36
    x['O_mid_(%)'] = df_slice['2FGM_O_10'].sum()/df_slice['2FGA_O_10'].sum()
    x['O_mid_rate'] = (df_slice['2FGA_O_10'].sum()/df_slice['MIN'].sum())*36
    x['T_mid_(%)'] = df_slice['2FGM_T_10'].sum()/df_slice['2FGA_T_10'].sum()
    x['T_mid_rate'] = (df_slice['2FGA_T_10'].sum()/df_slice['MIN'].sum())*36
    x['VT_mid_(%)'] = df_slice['2FGM_VT_10'].sum()/df_slice['2FGA_VT_10'].sum()
    x['VT_mid_rate'] = (df_slice['2FGA_VT_10'].sum()/df_slice['MIN'].sum())*36
    x['Tot_mid_(%)'] = df_slice['2FGM_10'].sum()/df_slice['2FGA_10'].sum()
    x['Tot_mid_rate'] = (df_slice['2FGA_10'].sum()/df_slice['MIN'].sum())*36
    
    x['WO_3P_(%)'] = df_slice['3PM_WO'].sum()/df_slice['3PA_WO'].sum()
    x['WO_3P_rate'] = (df_slice['3PA_WO'].sum()/df_slice['MIN'].sum())*36
    x['O_3P_(%)'] = df_slice['3PM_O'].sum()/df_slice['3PA_O'].sum()
    x['O_3P_rate'] = (df_slice['3PA_O'].sum()/df_slice['MIN'].sum())*36
    x['T_3P_(%)'] = df_slice['3PM_T'].sum()/df_slice['3PA_T'].sum()
    x['T_3P_rate'] = (df_slice['3PA_T'].sum()/df_slice['MIN'].sum())*36
    x['VT_3P_(%)'] = df_slice['3PM_VT'].sum()/df_slice['3PA_VT'].sum()
    x['VT_3P_rate'] = (df_slice['3PA_VT'].sum()/df_slice['MIN'].sum())*36
    x['Tot_3P_(%)'] = df_slice['3PM'].sum()/df_slice['3PA'].sum()
    x['Tot_3P_rate'] = (df_slice['3PA'].sum()/df_slice['MIN'].sum())*36
    x['OPEN_%'] = ((df_slice['3PM_WO'].sum())+(df_slice['3PM_O'].sum()))/((df_slice['3PA_WO'].sum())+(df_slice['3PA_O'].sum()))
    #x['CS_3P_rate'] = (df_slice['3PA_CS'].sum()/df_slice['MIN'].sum())*36
    #x['PU_3P_rate'] = (df_slice['3PA_PULLUP'].sum()/df_slice['MIN'].sum())*36
    
    return pd.Series(x, index=['WO_paint_(%)','WO_paint_rate','O_paint_(%)','O_paint_rate',
                              'T_paint_(%)','T_paint_rate','VT_paint_(%)','VT_paint_rate','Tot_paint_(%)','Tot_paint_rate',
                              'WO_mid_(%)','WO_mid_rate','O_mid_(%)','O_mid_rate',
                              'T_mid_(%)','T_mid_rate','VT_mid_(%)','VT_mid_rate','Tot_mid_(%)','Tot_mid_rate',
                              'WO_3P_(%)','WO_3P_rate','O_3P_(%)','O_3P_rate',
                              'T_3P_(%)','T_3P_rate','VT_3P_(%)','VT_3P_rate','Tot_3P_(%)','Tot_3P_rate','OPEN_%'])

In [1874]:
shooting_players = shooting_logs.groupby(['PLAYER','player_roles','3PM_q','3PM_q2','Mid_q','Paint_q']).apply(get_shooting_prob).round(3).reset_index()

/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:4: RuntimeWarning: invalid value encountered in scalar divide
  x['WO_paint_(%)'] = df_slice['2FGM_WO_paint'].sum()/df_slice['2FGA_WO_paint'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:21: RuntimeWarning: invalid value encountered in scalar divide
  x['VT_mid_(%)'] = df_slice['2FGM_VT_10'].sum()/df_slice['2FGA_VT_10'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:32: RuntimeWarning: invalid value encountered in scalar divide
  x['VT_3P_(%)'] = df_slice['3PM_VT'].sum()/df_slice['3PA_VT'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:26: RuntimeWarning: invalid value encountered in scalar divide
  x['WO_3P_(%)'] = df_slice['3PM_WO'].sum()/df_slice['3PA_WO'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:30: RuntimeWarning: invalid value encountered in scalar divide
  x['T_3P_(%)'] = df_slice['3PM_T'].sum()/df_slice['3PA_T'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:19: RuntimeWarning: invalid value encountered in scalar divide
  x['T_mid_(%)'] = df_slice['2FGM_T_10'].sum()/df_slice['2FGA_T_10'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:15: RuntimeWarning: invalid value encountered in scalar divide
  x['WO_mid_(%)'] = df_slice['2FGM_WO_10'].sum()/df_slice['2FGA_WO_10'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:28: RuntimeWarning: invalid value encountered in scalar divide
  x['O_3P_(%)'] = df_slice['3PM_O'].sum()/df_slice['3PA_O'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:34: RuntimeWarning: invalid value encountered in scalar divide
  x['Tot_3P_(%)'] = df_slice['3PM'].sum()/df_slice['3PA'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:36: RuntimeWarning: invalid value encountered in scalar divide
  x['OPEN_%'] = ((df_slice['3PM_WO'].sum())+(df_slice['3PM_O'].sum()))/((df_slice['3PA_WO'].sum())+(df_slice['3PA_O'].sum()))
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:17: RuntimeWarning: invalid value encountered in scalar divide
  x['O_mid_(%)'] = df_slice['2FGM_O_10'].sum()/df_slice['2FGA_O_10'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:6: RuntimeWarning: invalid value encountered in scalar divide
  x['O_paint_(%)'] = df_slice['2FGM_O_paint'].sum()/df_slice['2FGA_O_paint'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:23: RuntimeWarning: invalid value encountered in scalar divide
  x['Tot_mid_(%)'] = df_slice['2FGM_10'].sum()/df_slice['2FGA_10'].sum()
/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/915525588.py:8: RuntimeWarning: invalid value encountered in scalar divide
  x['T_paint_(%)'] = df_slice['2FGM_T_paint'].sum()/df_slice['2FGA_T_paint'].sum()

In [1875]:
shooting_players.fillna(0, inplace=True)

In [1876]:
shooting_players.columns

Index(['PLAYER', 'player_roles', '3PM_q', '3PM_q2', 'Mid_q', 'Paint_q',
       'WO_paint_(%)', 'WO_paint_rate', 'O_paint_(%)', 'O_paint_rate',
       'T_paint_(%)', 'T_paint_rate', 'VT_paint_(%)', 'VT_paint_rate',
       'Tot_paint_(%)', 'Tot_paint_rate', 'WO_mid_(%)', 'WO_mid_rate',
       'O_mid_(%)', 'O_mid_rate', 'T_mid_(%)', 'T_mid_rate', 'VT_mid_(%)',
       'VT_mid_rate', 'Tot_mid_(%)', 'Tot_mid_rate', 'WO_3P_(%)', 'WO_3P_rate',
       'O_3P_(%)', 'O_3P_rate', 'T_3P_(%)', 'T_3P_rate', 'VT_3P_(%)',
       'VT_3P_rate', 'Tot_3P_(%)', 'Tot_3P_rate', 'OPEN_%'],
      dtype='object')

In [1877]:
shooting_players_sm = shooting_players[['PLAYER', 'player_roles', '3PM_q', '3PM_q2', 'Mid_q', 'Paint_q', 'Tot_paint_(%)',
       'Tot_paint_rate','Tot_mid_(%)', 'Tot_mid_rate', 'Tot_3P_(%)', 'Tot_3P_rate', 'OPEN_%']]

In [1878]:
players_tot2 = players_gen.merge(shooting_players_sm, how='left')

In [1879]:
#players_tot2.loc[players_tot2['player_roles']=='None']

In [1880]:
drives_p = drives_player[['PLAYER','drives_q','DRIVES/MIN','DRIVE_SUCCESS_RATE','DRIVES_AST_RATE']]
drives_p.fillna(0, inplace=True)

/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/3030765034.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  drives_p.fillna(0, inplace=True)

In [1881]:
#drives_p

In [1882]:
players_tot3 = players_tot2.merge(drives_p, how='left')

In [1883]:
players_tot4 =  players_tot3.merge(rebs_players1[['PLAYER','UNCONTESTED_REB%','REB_group']], how='left')

In [1884]:
players_tot5 = players_tot4.merge(playing_td)

In [1885]:
players_tot5.columns

Index(['PLAYER', 'MIN', 'PTS', 'REB', 'AST', 'FG3M', 'GAME_DATE',
       'player_roles', '3PM_q', '3PM_q2', 'Mid_q', 'Paint_q', 'Tot_paint_(%)',
       'Tot_paint_rate', 'Tot_mid_(%)', 'Tot_mid_rate', 'Tot_3P_(%)',
       'Tot_3P_rate', 'OPEN_%', 'drives_q', 'DRIVES/MIN', 'DRIVE_SUCCESS_RATE',
       'DRIVES_AST_RATE', 'UNCONTESTED_REB%', 'REB_group', 'TEAM', 'OPPONENT'],
      dtype='object')

In [1886]:
players_3p = players_tot5[['PLAYER','TEAM', 'OPPONENT', 'MIN', 'FG3M', 'GAME_DATE',
       'player_roles', '3PM_q','Tot_3P_(%)', 'OPEN_%','3PM_q2',
       'Tot_3P_rate']]
threes_plus

,OPPONENT,3PM_q,WO_3P_rate,O_3P_rate,T_3P_rate,VT_3P_rate,Tot_3P_rate,WO_3P_rate_lg,O_3P_rate_lg,T_3P_rate_lg,VT_3P_rate_lg,Tot_3P_rate_lg,Three_Open_Rate+,DEF_3q
0,ATL,Bronze_cs,1.481292,0.818609,0.077963,0.000000,2.377863,1.896158,0.463195,0.044925,0.001549,2.405828,91.930714,MID
1,BKN,Bronze_cs,1.641127,0.169772,0.000000,0.000000,1.810898,1.896158,0.463195,0.044925,0.001549,2.405828,79.562077,MID
2,BOS,Bronze_cs,2.483695,0.479310,0.130721,0.000000,3.093726,1.896158,0.463195,0.044925,0.001549,2.405828,127.133443,BUNS
3,CHA,Bronze_cs,1.643233,0.589878,0.000000,0.000000,2.233111,1.896158,0.463195,0.044925,0.001549,2.405828,92.359493,MID
4,CHI,Bronze_cs,2.031501,0.586878,0.000000,0.000000,2.618379,1.896158,0.463195,0.044925,0.001549,2.405828,109.877664,BUNS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,SAC,Gold_pu,2.484974,1.610162,0.557851,0.000000,4.652986,2.683255,1.851601,0.476089,0.020159,5.031104,90.830201,ELITE
176,SAS,Gold_pu,2.958619,1.668028,0.316560,0.036526,4.979733,2.683255,1.851601,0.476089,0.020159,5.031104,103.904928,MID
177,TOR,Gold_pu,2.720956,1.954490,0.549301,0.000000,5.224747,2.683255,1.851601,0.476089,0.020159,5.031104,102.713200,MID
178,UTA,Gold_pu,2.925891,1.474840,0.559012,0.035682,4.995424,2.683255,1.851601,0.476089,0.020159,5.031104,99.782057,MID
179,WAS,Gold_pu,2.163514,1.817864,0.640093,0.012802,4.634273,2.683255,1.851601,0.476089,0.020159,5.031104,86.159262,ELITE

In [1887]:
players_3p_2 = players_3p.merge(picknpop23[['PLAYER','PickNPop']], how='left')
players_3p_3 = players_3p_2.merge(creator23[['PLAYER','Shot Creator']], how='left')
players_3p_4 = players_3p_3.merge(threes23[['PLAYER','3pt']], how='left')
players_3p_5 = players_3p_4.merge(secondary23[['PLAYER','Secondary Shooters']], how='left')

In [1888]:
players_3p_ = players_3p_5.merge(threes_plus[['OPPONENT','3PM_q','Three_Open_Rate+','DEF_3q']].rename(columns={'Three_Open_Rate+':'DEF_3_Rate+'}))
players_3p1 = players_3p_.merge(threes_plus2[['OPPONENT','3PM_q2','Three_Open_Rate+_2','DEF_3q2']].rename(columns={'Three_Open_Rate+_2':'DEF_3v2_Rate+'}))

In [1889]:
players_3p2 = players_3p1.merge(shooting3p_def_pr1[['OPPONENT','player_roles','PLUS_SHOT_RATE','OPEN_rank']].rename(columns={'PLUS_SHOT_RATE':'DEF_3P_rate','OPEN_rank':'DEF_3p_rank'}))

In [1890]:
pnp_3logs.head(5)

          PLAYER pnp_3q  trys_pnp  3PM/G_pnp  3PM_O_pnp  3PM_O+_pnp
0   Aaron Gordon   BUNS      20.0        0.8       0.55        0.20
1   Aaron Gordon  ELITE      14.0        0.5       0.36        0.14
2   Aaron Gordon    MID      17.0        0.3       0.24        0.06
3  Aaron Holiday   BUNS      19.0        1.0       0.42        0.21
4  Aaron Holiday  ELITE      13.0        1.0       0.31        0.23

In [1891]:
pnp

,OPPONENT,Games_pnp,PTS_OVER_pnp,3PM_OVER_pnp,PTS_dif_pnp,Paint_plus_pnp,Mid_plus_pnp,3p_plus_pnp,pnp_q,pnp_3q
0,ATL,62.0,0.564516,0.27,1.707693,0.733308,-0.115790,0.206491,BUNS,MID
1,BKN,60.0,0.383333,0.23,-1.527818,-0.082756,-0.006448,-0.383054,ELITE,ELITE
2,BOS,59.0,0.457627,0.29,-1.622865,-0.752919,0.022028,0.818239,ELITE,BUNS
3,CHA,64.0,0.578125,0.34,1.964078,0.488074,-0.102182,0.963278,BUNS,BUNS
4,CHI,62.0,0.500000,0.37,0.605988,-0.629512,-0.041733,1.008268,BUNS,BUNS
5,CLE,63.0,0.507937,0.30,0.746910,-0.112823,0.098928,0.044667,BUNS,BUNS
6,DAL,54.0,0.518519,0.31,0.188119,0.078409,-0.097708,0.637269,BUNS,BUNS
7,DEN,59.0,0.474576,0.19,-0.213354,0.560415,0.095701,-0.706180,MID,ELITE
8,DET,55.0,0.600000,0.35,1.951683,-0.013780,-0.102667,0.257568,BUNS,BUNS
9,GSW,44.0,0.568182,0.25,0.506447,-0.240078,0.100087,0.229056,BUNS,MID
10,HOU,64.0,0.390625,0.14,-1.394206,-0.036257,-0.204070,-0.212896,ELITE,MID
11,IND,59.0,0.423729,0.17,-0.622623,0.203611,-0.119819,-1.487815,MID,ELITE
12,LAC,67.0,0.477612,0.24,-0.352776,0.113057,0.068467,-0.316389,MID,ELITE
13,LAL,53.0,0.415094,0.38,-1.281625,-0.558393,0.152978,1.720954,ELITE,BUNS
14,MEM,58.0,0.517241,0.28,-0.076499,-0.055983,0.191320,0.216922,MID,MID
15,MIA,61.0,0.459016,0.21,-1.568833,0.216391,-0.007803,-0.201014,ELITE,MID
16,MIL,60.0,0.450000,0.27,-0.260124,-0.164338,-0.345728,0.561852,MID,BUNS
17,MIN,69.0,0.362319,0.25,-1.557016,-0.522443,0.278471,0.125147,ELITE,MID
18,NOP,67.0,0.343284,0.18,-2.127098,-0.333460,0.004368,0.026542,ELITE,MID
19,NYK,69.0,0.376812,0.17,-2.593227,-0.591265,0.008927,0.060856,ELITE,MID
20,OKC,59.0,0.457627,0.20,-0.584479,-0.042045,-0.240669,0.090453,MID,MID
21,ORL,59.0,0.406780,0.15,-1.744328,-0.344089,0.045339,-0.539358,ELITE,ELITE
22,PHI,69.0,0.478261,0.22,0.915896,0.580036,-0.124859,-0.344503,BUNS,ELITE
23,PHX,66.0,0.469697,0.21,-0.475250,0.095002,-0.066180,-0.223431,MID,MID
24,POR,62.0,0.532258,0.26,0.405433,0.178295,0.051962,-0.342999,BUNS,ELITE
25,SAC,60.0,0.500000,0.32,0.876848,0.181198,-0.023252,-0.512507,BUNS,BUNS
26,SAS,56.0,0.625000,0.30,1.343334,0.104238,0.232394,0.439297,BUNS,BUNS
27,TOR,54.0,0.407407,0.30,-0.539966,-0.261745,0.100857,-0.146753,MID,BUNS
28,UTA,57.0,0.631579,0.37,2.180224,0.452471,0.350580,0.784835,BUNS,BUNS
29,WAS,57.0,0.491228,0.25,1.657339,0.994628,0.049067,-0.310553,BUNS,ELITE

In [1892]:

players_3p3 = players_3p2.merge(pnp)
players_3p4 = players_3p3.merge(pnp_3logs)
players_3p5 = players_3p4.merge(creator_d)
players_3p6 = players_3p5.merge(creator_3logs)
players_3p7 = players_3p6.merge(threes_d)
players_3p8 = players_3p7.merge(threes_3logs)
players_3p9 = players_3p8.merge(secondary_d)
players_3p10 = players_3p9.merge(secondary_3logs)

In [1893]:
players_3p10['GAME_DATE'] = td

In [1894]:
players_3p10.loc[players_3p10['PLAYER']=='Lauri Markkanen']

,PLAYER,TEAM,OPPONENT,MIN,FG3M,GAME_DATE,player_roles,3PM_q,Tot_3P_(%),OPEN_%,...,PTS_dif_secondary,Paint_plus_secondary,Mid_plus_secondary,3p_plus_secondary,secondary_q,secondary_3q,trys_secondary,3PM/G_secondary,3PM_O_secondary,3PM_O+_secondary
215,Lauri Markkanen,UTA,HOU,32.65,3.2,2024-03-29,Pick N Pop Bigs,Diamond_pu,0.4,0.413,...,-0.817636,0.082084,-0.239754,0.144384,ELITE,MID,23.0,3.3,0.57,0.43

In [1895]:
players_3p2_past = pd.read_csv('players_3p_logs_23.csv')
players_3p2_past = players_3p2_past.loc[:, ~players_3p2_past.columns.str.contains('^Unnamed')]
pd.concat([players_3p2_past,players_3p10]).drop_duplicates(subset=['PLAYER','GAME_DATE'], keep='last').to_csv('players_3p_logs_23.csv', index= False)
#players_3p2.to_csv('players_3p_logs_23.csv')

/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/3330336336.py:1: DtypeWarning: Columns (16,22,24,25,26,35,56,57) have mixed types. Specify dtype option on import or set low_memory=False.
  players_3p2_past = pd.read_csv('players_3p_logs_23.csv')

In [1896]:
from gspread_pandas import Spread, Client
spread = Spread('NBA 2023 v2')
spread.df_to_sheet(players_3p10, index=False,sheet='TODAY 3p2',replace=True)

In [1897]:
players_reb = players_tot5[['PLAYER','TEAM', 'OPPONENT', 'MIN', 'REB', 'GAME_DATE',
       'player_roles', 'UNCONTESTED_REB%', 'REB_group']]
rebs_team1

,OPPONENT,REB_group,REB,UNCONTESTED_REB%,UNCONTESTED_REB/36MIN,REB/36MIN,REB +/-,Reb_rank,UNCONTESTED_Rate+,UC_REBq,as of Date
0,NYK,Platinum,783.0,0.549170,5.733121,10.439613,-119.666939,1.0,82.134469,ELITE,2024-03-02
1,PHX,Platinum,779.0,0.584082,5.854809,10.023948,-86.519414,2.0,83.877814,ELITE,2024-03-02
2,OKC,Platinum,926.0,0.584233,6.924800,11.852800,4.783545,3.0,99.206832,MID,2024-03-02
3,POR,Platinum,760.0,0.590789,6.717925,11.371098,-51.611141,4.0,96.243081,MID,2024-03-02
4,GSW,Platinum,804.0,0.590796,6.676558,11.300953,-29.566914,5.0,95.650438,MID,2024-03-02
...,...,...,...,...,...,...,...,...,...,...,...
85,WAS,Bronze,555.0,0.790991,3.861415,4.881744,68.333356,26.0,114.780818,BUNS,2024-03-02
86,DEN,Bronze,459.0,0.797386,3.257355,4.085043,-12.407533,27.0,96.825083,ELITE,2024-03-02
87,CHI,Bronze,514.0,0.801556,3.277211,4.088559,1.735101,28.0,97.415301,ELITE,2024-03-02
88,LAL,Bronze,516.0,0.808140,3.606400,4.462595,65.342382,29.0,107.200471,BUNS,2024-03-02
89,CHA,Bronze,589.0,0.818336,3.634383,4.441186,35.563758,30.0,108.032284,BUNS,2024-03-02

In [1898]:
players_reb1 = players_reb.merge(rebs_team1[['OPPONENT','REB_group','REB','UNCONTESTED_REB%','Reb_rank','REB +/-','UNCONTESTED_Rate+','UC_REBq']].rename(columns={'REB':'DEF_TOT_REB','UNCONTESTED_REB%':'DEF_UCReb%','Reb_rank':'Def_rank','REB +/-':'DEF UC +/-'}))

In [1899]:
players_reb2 = players_reb1.merge(BigMen23[['PLAYER','Big Men REB']], how='left')
players_reb3 = players_reb2.merge(BHReb23[['PLAYER','BH Reb']], how='left')
players_reb4 = players_reb3.merge(WingReb23[['PLAYER','Wing Reb']], how='left')
players_reb5 = players_reb4.merge(WingReb_d)
players_reb6 = players_reb5.merge(wing_logs)
players_reb7 = players_reb6.merge(BHReb_d)
players_reb8 = players_reb7.merge(BH_logs)
players_reb9 = players_reb8.merge(BigMen_d)
players_reb10 = players_reb9.merge(bigmen_logs)

In [1900]:
players_reb10['GAME_DATE'] = td

In [1901]:
players_reb10

,PLAYER,TEAM,OPPONENT,MIN,REB,GAME_DATE,player_roles,UNCONTESTED_REB%,REB_group,DEF_TOT_REB,...,Games_bigmen,rebs_dif_bigmen,rebs_OVER_bigmen,UNC_rebs_dif_bigmen,UNC_rebs_OVER_bigmen,bigmen_q,trys_bigmen,REBS/G_bigmen,REBS_O_bigmen,REBS_O+_bigmen
0,Aaron Gordon,DEN,MIN,31.46,6.52,2024-03-29,Versitile Bigs,0.552469,Gold,877.0,...,87.0,-81.170064,0.160920,-42.044151,0.172414,ELITE,46.0,6.8,0.478261,0.195652
1,Christian Braun,DEN,MIN,19.15,3.52,2024-03-29,Non-Offense,0.700980,Gold,877.0,...,87.0,-81.170064,0.160920,-42.044151,0.172414,ELITE,42.0,3.5,0.404762,0.142857
2,Michael Porter Jr.,DEN,MIN,31.67,7.10,2024-03-29,Run Around Guards,0.701370,Gold,877.0,...,87.0,-81.170064,0.160920,-42.044151,0.172414,ELITE,43.0,5.8,0.372093,0.139535
3,Peyton Watson,DEN,MIN,18.20,2.86,2024-03-29,None,0.767123,Gold,877.0,...,87.0,-81.170064,0.160920,-42.044151,0.172414,ELITE,22.0,2.9,0.272727,0.090909
4,DeAndre Jordan,DEN,MIN,11.28,4.55,2024-03-29,Role Big Men,0.460317,Platinum,741.0,...,87.0,-81.170064,0.160920,-42.044151,0.172414,ELITE,22.0,6.0,0.545455,0.272727
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
248,P.J. Washington,DAL,SAC,29.55,5.29,2024-03-29,Pick N Pop Bigs,0.716102,Gold,837.0,...,87.0,-18.730897,0.206897,-8.392678,0.183908,ELITE,42.0,4.7,0.476190,0.214286
249,Derrick Jones Jr.,DAL,SAC,24.17,3.53,2024-03-29,Role Big Men,0.679348,Bronze,491.0,...,87.0,-18.730897,0.206897,-8.392678,0.183908,ELITE,29.0,3.3,0.517241,0.172414
250,Josh Green,DAL,SAC,27.53,3.32,2024-03-29,Glue Guys,0.837838,Bronze,491.0,...,87.0,-18.730897,0.206897,-8.392678,0.183908,ELITE,42.0,3.2,0.404762,0.119048
251,Maxi Kleber,DAL,SAC,22.11,3.52,2024-03-29,3pt Wings,0.666667,Bronze,491.0,...,87.0,-18.730897,0.206897,-8.392678,0.183908,ELITE,21.0,3.4,0.428571,0.095238
252,Tim Hardaway Jr.,DAL,SAC,29.33,3.61,2024-03-29,Run Around Guards,0.803191,Bronze,491.0,...,87.0,-18.730897,0.206897,-8.392678,0.183908,ELITE,46.0,3.8,0.478261,0.195652

In [1902]:
players_reb1_past = pd.read_csv('players_reb_logs_23.csv')
players_reb1_past = players_reb1_past.loc[:, ~players_reb1_past.columns.str.contains('^Unnamed')]
pd.concat([players_reb1_past,players_reb10]).drop_duplicates(subset=['PLAYER','GAME_DATE']).to_csv('players_reb_logs_23.csv', index=False)
#players_reb1.to_csv('players_reb_logs_23.csv')

In [1903]:
from gspread_pandas import Spread, Client
spread = Spread('NBA 2023 v2')
spread.df_to_sheet(players_reb10, index=False,sheet='TODAY REB2',replace=True)

In [1904]:
players_pts = players_tot5[['PLAYER','TEAM', 'OPPONENT', 'MIN', 'PTS','FG3M', 'GAME_DATE',
       'player_roles', '3PM_q2','3PM_q', 'Mid_q', 'Paint_q', 'drives_q',
       'Tot_paint_rate', 'Tot_mid_rate','Tot_3P_rate']]

In [1905]:
#players_pts3.loc[players_pts3['player_roles']=='None']

In [1906]:
players_pts_1 = players_pts.merge(downhill23[['PLAYER','Downhill']], how='left')
players_pts_2 = players_pts_1.merge(picknroll23[['PLAYER','PickNRoll']], how='left')
players_pts_3 = players_pts_2.merge(picknpop23[['PLAYER','PickNPop']], how='left')
players_pts_4 = players_pts_3.merge(threes23[['PLAYER','3pt']], how='left')
players_pts_5 = players_pts_4.merge(creator23[['PLAYER','Shot Creator']], how='left')
players_pts_6 = players_pts_5.merge(secondary23[['PLAYER','Secondary Shooters']], how='left')
players_pts_7 = players_pts_6.merge(sc23[['PLAYER','Secondary Creators']], how='left')

In [1907]:
sc23[['PLAYER','Secondary Creators']]

                  PLAYER Secondary Creators
33         Austin Reaves                Yes
61           CJ McCollum                Yes
69         Cameron Payne                Yes
70          Caris LeVert                Yes
85            Coby White                Yes
89          Cole Anthony                Yes
96      Craig Porter Jr.                Yes
97      D'Angelo Russell                Yes
115       Darius Garland                Yes
130      Dennis Schroder                Yes
136        Derrick White                Yes
168        Fred VanVleet                Yes
193    Immanuel Quickley                Yes
224          Jalen Green                Yes
238         James Harden                Yes
278      Jordan Clarkson                Yes
285         Jordan Poole                Yes
330       Keyonte George                Yes
331      Khris Middleton                Yes
364      Malcolm Brogdon                Yes
367           Malik Monk                Yes
371        Marcus Sasser                Yes
390        Mikal Bridges                Yes
456       Reggie Jackson                Yes
476      Scoot Henderson                Yes
492       T.J. McConnell                Yes
494  Talen Horton-Tucker                Yes
544          Zach LaVine                Yes

In [1908]:
players_pts1 = players_pts_7.merge(threes_plus[['OPPONENT','3PM_q','Three_Open_Rate+','DEF_3q']].rename(columns={'Three_Open_Rate+':'DEF_3_Rate+'}),how='left')
players_pts1_ = players_pts1.merge(threes_plus2[['OPPONENT','3PM_q2','Three_Open_Rate+_2','DEF_3q2']].rename(columns={'Three_Open_Rate+_2':'DEF_3v2_Rate+'}),how='left')
players_pts2 = players_pts1_.merge(mid_plus[['OPPONENT','Mid_q','Mid_Open_Rate+','DEF_MIDq']].rename(columns={'Mid_Open_Rate+':'DEF_Mid_Rate+'}),how='left')

In [1909]:
paint = paint_plus.groupby(['OPPONENT'])['Tot_paint_rate'].sum().reset_index()
paint["Paint_rank"] = paint['Tot_paint_rate'].rank(method="dense")
players_pts3 = players_pts2.merge(paint[['OPPONENT','Paint_rank']].rename(columns={'Paint_rank':'DEF_Paint_rank'}),how='left')

In [1910]:
#players_pts4 = players_pts3.merge(dh)
#players_pts5 = players_pts4.merge(picknroll)
#players_pts6 = players_pts5.merge(picknpop)
#players_pts7 = players_pts6.merge(threes)
#players_pts8 = players_pts7.merge(creator)
#players_pts9 = players_pts8.merge(secondary)

In [1911]:
players_pts4 = players_pts3.merge(drives_team_vs[['OPPONENT','drives_q','Drive_rank']].rename(columns={'Drive_rank':'DEF_Drive_rank'}), how='left')

In [1912]:
#players_pts10.loc[players_pts10['player_roles'].isna()]

In [1913]:
players_pts5 = players_pts4.merge(dh,how='left')
players_pts6 = players_pts5.merge(dh_logs,how='left')
players_pts7 = players_pts6.merge(pnr,how='left')
players_pts8 = players_pts7.merge(pnr_logs,how='left')
players_pts9 = players_pts8.merge(pnp,how='left')
players_pts10 = players_pts9.merge(pnp_logs,how='left')
players_pts11 = players_pts10.merge(threes_d,how='left')
players_pts12 = players_pts11.merge(threes_logs,how='left')
players_pts13 = players_pts12.merge(creator_d,how='left')
players_pts14 = players_pts13.merge(creator_logs,how='left')
players_pts15 = players_pts14.merge(sc_d,how='left')
players_pts16 = players_pts15.merge(sc_logs,how='left')
players_pts17 = players_pts16.merge(secondary_d,how='left')
players_pts18 = players_pts17.merge(secondary_logs,how='left')

In [1914]:
players_pts18['GAME_DATE'] = td

In [1915]:
threes_logs.loc[threes_logs['PLAYER']=='Julius Randle']

,PLAYER,threes_q,trys_threes,PTS/G_threes,PTS_O_threes,PTS_O+_threes
552,Julius Randle,BUNS,15.0,26.0,0.60,0.27
553,Julius Randle,ELITE,19.0,22.5,0.32,0.21
554,Julius Randle,MID,12.0,23.7,0.58,0.17

In [1916]:
players_pts10.loc[players_pts10['PLAYER']=='Julius Randle']

,PLAYER,TEAM,OPPONENT,MIN,PTS,FG3M,GAME_DATE,player_roles,3PM_q2,3PM_q,...,PTS_dif_pnp,Paint_plus_pnp,Mid_plus_pnp,3p_plus_pnp,pnp_q,pnp_3q,trys_pnp,PTS/G_pnp,PTS_O_pnp,PTS_O+_pnp
224,Julius Randle,NYK,SAS,35.44,23.96,1.65,46,Pick N Pop Bigs,Gold,Gold_pu,...,1.343334,0.104238,0.232394,0.439297,BUNS,BUNS,17.0,23.6,0.53,0.29

In [1917]:
players_pts4_past = pd.read_csv('players_pts_logs_23.csv')
players_pts4_past = players_pts4_past.loc[:, ~players_pts4_past.columns.str.contains('^Unnamed')]
pd.concat([players_pts4_past,players_pts18]).drop_duplicates(subset=['PLAYER','GAME_DATE'],keep='last').to_csv('players_pts_logs_23.csv', index=False)
#players_pts4.to_csv('players_pts_logs_23.csv')

/var/folders/sj/rsx4zyld6flczf6q6r20b1c80000gn/T/ipykernel_3959/1561109223.py:1: DtypeWarning: Columns (72,79,86,87,94,95,102,103,110,111,123,128) have mixed types. Specify dtype option on import or set low_memory=False.
  players_pts4_past = pd.read_csv('players_pts_logs_23.csv')

In [1918]:
from gspread_pandas import Spread, Client
spread = Spread('NBA 2023 v2')
spread.df_to_sheet(players_pts18, index=False,sheet='TODAY PTS2',replace=True)

In [1919]:
players_ast = players_tot5[['PLAYER','TEAM', 'OPPONENT', 'MIN', 'AST','GAME_DATE',
       'player_roles' ,'drives_q', 'DRIVES/MIN', 'DRIVE_SUCCESS_RATE',
       'DRIVES_AST_RATE', 'TEAM']]

In [1406]:
def_ast = gamelogs.merge(ptypes[['PLAYER','player_roles']]).groupby(['OPPONENT','player_roles'])['AST'].mean().round(2).reset_index()

In [1407]:
players_ast1 = players_ast.merge(def_ast.rename(columns={'AST':'DEF_AST'}))

In [1408]:


from gspread_pandas import Spread, Client
spread = Spread('NBA 2023')
spread.df_to_sheet(players_ast1, index=False,sheet='TODAY ASSISTS2',replace=True)

In [1409]:

from gspread_pandas import Spread, Client
spread = Spread('NBA 2023')
spread.df_to_sheet(pass_drives, index=False,sheet='Drives Log',replace=True)

from gspread_pandas import Spread, Client
spread = Spread('NBA 2023')
spread.df_to_sheet(rebs_gl, index=False,sheet='Reb Log',replace=True)

from gspread_pandas import Spread, Client
spread = Spread('NBA 2023')
spread.df_to_sheet(shooting_logs, index=False,sheet='Shooting Log',replace=True)

APIError: <!DOCTYPE html>
<html lang=en>
  <meta charset=utf-8>
  <meta name=viewport content="initial-scale=1, minimum-scale=1, width=device-width">
  <title>Error 502 (Server Error)!!1</title>
  <style>
    *{margin:0;padding:0}html,code{font:15px/22px arial,sans-serif}html{background:#fff;color:#222;padding:15px}body{margin:7% auto 0;max-width:390px;min-height:180px;padding:30px 0 15px}* > body{background:url(//www.google.com/images/errors/robot.png) 100% 5px no-repeat;padding-right:205px}p{margin:11px 0 22px;overflow:hidden}ins{color:#777;text-decoration:none}a img{border:0}@media screen and (max-width:772px){body{background:none;margin-top:0;max-width:none;padding-right:0}}#logo{background:url(//www.google.com/images/branding/googlelogo/1x/googlelogo_color_150x54dp.png) no-repeat;margin-left:-5px}@media only screen and (min-resolution:192dpi){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat 0% 0%/100% 100%;-moz-border-image:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) 0}}@media only screen and (-webkit-min-device-pixel-ratio:2){#logo{background:url(//www.google.com/images/branding/googlelogo/2x/googlelogo_color_150x54dp.png) no-repeat;-webkit-background-size:100% 100%}}#logo{display:inline-block;height:54px;width:150px}
  </style>
  <a href=//www.google.com/><span id=logo aria-label=Google></span></a>
  <p><b>502.</b> <ins>That’s an error.</ins>
  <p>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.  <ins>That’s all we know.</ins>

In [1425]:
x = (shooting_logs['3PA_WO'].sum()/shooting_logs['MIN'].sum())*36
y = (shooting_logs['3PA_O'].sum()/shooting_logs['MIN'].sum())*36

In [1426]:
y

1.879249811492632

In [1427]:
threes_prop_def = shooting_logs.groupby(['OPPONENT']).apply(get_shooting_prob).reset_index()[['OPPONENT','WO_3P_rate','O_3P_rate','T_3P_rate','VT_3P_rate','Tot_3P_rate']]
threes_prop_def['WO_3P_rate_lg'] = x
threes_prop_def['O_3P_rate_lg'] = y
threes_prop_def['Three_Open_Rate+'] = 100*(((threes_prop_def['WO_3P_rate']*.6)+(threes_prop_def['O_3P_rate']*.4))/((threes_prop_def['WO_3P_rate_lg']*.6)+(threes_prop_def['O_3P_rate_lg']*.4)))

In [1428]:
threes_prop_def

,OPPONENT,WO_3P_rate,O_3P_rate,T_3P_rate,VT_3P_rate,Tot_3P_rate,WO_3P_rate_lg,O_3P_rate_lg,Three_Open_Rate+
0,ATL,2.792387,2.002496,0.552306,0.009257,5.356446,2.749717,1.87925,103.118864
1,BKN,2.819814,1.964938,0.462526,0.015949,5.263228,2.749717,1.87925,103.178550
2,BOS,3.209918,1.921747,0.507461,0.042038,5.681165,2.749717,1.87925,112.205546
3,CHA,2.740981,1.933915,0.514695,0.027410,5.217001,2.749717,1.87925,100.692256
4,CHI,2.971845,2.167033,0.608081,0.029808,5.776766,2.749717,1.87925,110.342995
5,CLE,2.532904,1.944797,0.538320,0.037340,5.053361,2.749717,1.87925,95.674887
6,DAL,2.920002,1.802589,0.643553,0.041623,5.407767,2.749717,1.87925,102.977546
7,DEN,2.345753,1.747570,0.548073,0.025055,4.666451,2.749717,1.87925,87.714076
8,DET,2.332193,1.946048,0.419856,0.042905,4.741002,2.749717,1.87925,90.681139
9,GSW,3.011166,1.825456,0.542613,0.023446,5.402681,2.749717,1.87925,105.636075
10,HOU,2.659915,1.937850,0.648007,0.033943,5.279716,2.749717,1.87925,98.732443
11,IND,2.065552,1.754511,0.543566,0.021139,4.384768,2.749717,1.87925,80.829126
12,LAC,2.708062,1.906824,0.555898,0.027950,5.198735,2.749717,1.87925,99.418578
13,LAL,3.291466,1.682237,0.529311,0.030420,5.533434,2.749717,1.87925,110.253638
14,MEM,2.993464,1.641770,0.505390,0.023924,5.164548,2.749717,1.87925,102.134326
15,MIA,2.621330,2.167460,0.660736,0.021613,5.471139,2.749717,1.87925,101.592819
16,MIL,2.751336,1.796791,0.585139,0.026597,5.159864,2.749717,1.87925,98.667026
17,MIN,2.491061,1.760667,0.537404,0.035629,4.824762,2.749717,1.87925,91.562611
18,NOP,3.051387,2.218076,0.511628,0.015318,5.796409,2.749717,1.87925,113.180448
19,NYK,2.597176,2.029043,0.601198,0.024048,5.251465,2.749717,1.87925,98.683868
20,OKC,2.839566,1.992027,0.649574,0.027839,5.509005,2.749717,1.87925,104.123214
21,ORL,2.417542,1.894095,0.520422,0.018154,4.850213,2.749717,1.87925,91.948184
22,PHI,2.754458,1.596157,0.614862,0.024843,4.990320,2.749717,1.87925,95.403248
23,PHX,2.782679,1.948186,0.539784,0.034124,5.304773,2.749717,1.87925,101.971734
24,POR,2.584747,1.867307,0.432429,0.026208,4.910691,2.749717,1.87925,95.679458
25,SAC,2.697540,1.820760,0.595187,0.016000,5.129486,2.749717,1.87925,97.722194
26,SAS,3.059171,1.747671,0.424221,0.026887,5.257949,2.749717,1.87925,105.539827
27,TOR,2.741211,1.848514,0.577097,0.030057,5.196879,2.749717,1.87925,99.275551
28,UTA,3.111973,1.753757,0.546777,0.017450,5.429956,2.749717,1.87925,106.960410
29,WAS,2.572197,1.762374,0.645376,0.018617,4.998564,2.749717,1.87925,93.618135

In [1429]:
threes_plus.loc[threes_plus['3PM_q']=='Platinum'].sort_values(by='Three_Open_Rate+')

Empty DataFrame
Columns: [OPPONENT, 3PM_q, WO_3P_rate, O_3P_rate, T_3P_rate, VT_3P_rate, Tot_3P_rate, WO_3P_rate_lg, O_3P_rate_lg, T_3P_rate_lg, VT_3P_rate_lg, Tot_3P_rate_lg, Three_Open_Rate+, DEF_3q]
Index: []

In [1430]:
def_ast = gamelogs.merge(ptypes[['PLAYER','player_roles']]).groupby(['OPPONENT','player_roles'])['AST'].mean().round(2).reset_index()

In [1431]:
def_ast

    OPPONENT             player_roles   AST
0        ATL                3pt Wings  1.56
1        ATL                Glue Guys  2.05
2        ATL              Non-Offense  1.55
3        ATL          Pick N Pop Bigs  2.05
4        ATL    Primary Ball Handlers  7.47
..       ...                      ...   ...
325      WAS             Role Big Men  1.55
326      WAS                 Role G/W  3.15
327      WAS        Run Around Guards  1.84
328      WAS  Secondary Ball Handlers  5.13
329      WAS           Versitile Bigs  3.72

[330 rows x 3 columns]